name: Unsquashing + releasing pop-os rootfs
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  unpack-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get install -y curl squashfs-tools

      - name: Unpacking + Repacking pop-os rootfs
        run: sudo bash unpack_iso.sh

      - name: Splitting tar archive
        run: sudo split --verbose -b 1900MB /tmp/pop-os/pop-os-rootfs-22.04.tar.xz /tmp/pop-os/pop-os-rootfs-22.04.split.

      - name: Generating release tag
        id: tag
        run: |
          date=$(date +"%Y.%m.%d_%H-%M")
          echo "release_tag=$date" >> $GITHUB_OUTPUT

      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Automated Pop!_OS rootfs extraction - ${{ steps.tag.outputs.release_tag }}
          body: |
            These are completely **unmodified** pop-os rootfs archives for the depthboot builder script.  
            Please download official images at https://pop.system76.com/
          files: |
            /tmp/pop-os/pop-os-rootfs-22.04.split.*
            /tmp/pop-os/pop-os-rootfs-22.04.sha256
